### ISSUE TITLE
Could not detect language based on extension.

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dolos#1558]
**Describe the bug**
```
could not detect language based on extension.
Please specify the language with the --language flag.Error: Could not detect language based on extension.
    at LanguagePicker.detectLanguage (file:///usr/local/lib/node_modules/@dodona/dolos/node_modules/@dodona/dolos-lib/dist/lib/language.js:113:19)
    at Dolos.analyze (file:///usr/local/lib/node_modules/@dodona/dolos/node_modules/@dodona/dolos-lib/dist/lib/dolos.js:117:53)
    at Dolos.analyzePaths (file:///usr/local/lib/node_modules/@dodona/dolos/node_modules/@dodona/dolos-lib/dist/lib/dolos.js:108:21)
    at async file:///usr/local/lib/node_modules/@dodona/dolos/dist/cli/commands/run.js:77:24
    at async tryCatch (file:///usr/local/lib/node_modules/@dodona/dolos/dist/cli/util/utils.js:102:9)
    at async run (file:///usr/local/lib/node_modules/@dodona/dolos/dist/cli/commands/run.js:62:5)
```

**To Reproduce**
1. Go to https://dodona.be/en/evaluations/???/
2. Click on 'Detect plagiarism' of a **HTML**-exercise
3. Oops! Something went wrong: non-zero exit code

**Expected behavior**
Message that HTML is not supported.

**Screenshots**
![image](https://github.com/dodona-edu/dolos/assets/56451049/e343f7be-973e-49ad-bc87-fc10ccd4c980)
![image](https://github.com/dodona-edu/dolos/assets/56451049/97437bb6-3184-41ca-b87c-684eb1f9f4e2)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Additional context**
- What files were you analyzing? Dodona submissions
- Which language? HTML
- How many? 28

**Comment by rien** [comment]
The same error is shown when a ZIP-file is submitted with no submissions. This error message should be different.
