### ISSUE TITLE
Cannot run sample code for @dodona/dolos-lib

### ISSUE THREAD

**Issue by fabianTMC** [dodona-edu/dolos#797]
After I install `@dodona/dolos-lib` and then manually add `d3-dsv` because of #796, I get the following:

```bash
/home/fabian/dev/tmp/dolos-test/node_modules/@dodona/dolos-lib/dist/dolos.js:34
const d3_dsv_1 = require("d3-dsv");
                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/fabian/dev/tmp/dolos-test/node_modules/d3-dsv/src/index.js from /home/fabian/dev/tmp/dolos-test/node_modules/@dodona/dolos-lib/dist/dolos.js not supported.
Instead change the require of index.js in /home/fabian/dev/tmp/dolos-test/node_modules/@dodona/dolos-lib/dist/dolos.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/fabian/dev/tmp/dolos-test/node_modules/@dodona/dolos-lib/dist/dolos.js:34:18)
    at Object.<anonymous> (/home/fabian/dev/tmp/dolos-test/node_modules/@dodona/dolos-lib/dist/index.js:34:15)
    at Object.<anonymous> (/home/fabian/dev/tmp/dolos-test/index.js:1:15) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v17.1.0
```

**Comment by rien** [comment]
This issue should be resolved now. Feel free to reopen or to create a new issue if you encounter another problem.
